/**
* Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  guidesSidebar: [
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "First steps";
        }
      })(),
      defaultStyle: true,
    },
    "welcome",
    "faq",
    "free-vs-pro",
    {
      type: 'category',
      label: 'Pro Control Panel',
      items: [
        "dashboard",
        "serverlist",
        "editserver"
      ]
    }, 
    "network-analysis",
    "firststeps-locations",   
    {
      type: 'category',
      label: 'Support',
      items: [
        "contactsupport",
        "create-screenshots"
      ]
    },
    {
      type: 'category',
      label: 'Account',
      items: [
        "banned",
        "account-termination-and-cancellation-period",
        "account-paymentoptions",
      ]
    },
  ],
  
  
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  gameserverSidebar: [
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "First steps";
        }
      })(),
      defaultStyle: true,
    },
    "gameserver-server-down-what-now",
    "serverfaqs",
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "All Games (A-Z)";
        }
      })(),
      defaultStyle: true,
    },
    {
      type: "category",
      label: "Call of Duty",
      items: [
        "cod-firststeps-dashboard",
        "cod-rcon"
      ],
    },
    {
      type: "category",
      label: "Call of Duty 2",
      items: [
        "cod2-firststeps-dashboard",
        "cod2-rcon"
      ],
    },
    {
      type: "category",
      label: "Call of Duty 4: Modern Warfare",
      items: [
        "cod4-firststeps-dashboard",
        "cod4-rcon",
        {
          type: "category",
          label: "Mods",
          items: [
            "cod4-promodlive",
	          "cod4-fpspromod",
            "cod4-gungame",
            "cod4-jumper",
	          "cod4-stockmaps"
          ]
        },
      ],
    },
    {
      type: "category",
      label: "Call of Duty: United Offensive",
      items: [
        "coduo-firststeps-dashboard",
        "coduo-rcon"
      ],
    },    
    {
      type: "category",
      label: "Counter-Strike: 1.6",
      items: [
        "cs16-becomeadmin",
        "cs16-rcon"
      ],
    },
    {
      type: "category",
      label: "Counter-Strike: Condition Zero",
      items: [
        "cscz-firststeps-dashboard",
        "cscz-becomeadmin",
        "cscz-rcon"
      ],
    },
    {
      type: "category",
      label: "Counter-Strike: Source",
      items: [
        "css-firststeps-dashboard",
        "css-rcon"
      ],
    },
    {
      type: "category",
      label: "Counter-Strike: 2",
      items: [
        "source-gsltoken",
        "cs2-pluginslist",
        {
          type: "category",
          label: "Configuration & Administration",
          items: [
            "cs2-becomeadmin",
            "cs2-rcon"
          ]
        },
        {
          type: "category",
          label: "Plugins: Pro List",
          items: [
            "cs2-matchzy",
            "cs2-retakes",
            "cs2-skins",
            "cs2-simpleadmin",
            "cs2-cstv2discord",
            "cs2-deathmatch",
            "cs2-customadmins",
            "cs2-openprefireprac"
          ]
        },
      ],
    },
    {
      type: "category",
      label: "Half-Life: Deathmatch",
      items: [
        "hldm-firststeps-dashboard",
        "hldm-rcon"
      ],
    }, 
  ],
};

export default sidebars;
