/**
* Creating a sidebar enables you to:
- create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  guidesSidebar: [
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "First steps";
        }
      })(),
      defaultStyle: true,
    },
    'welcome',
    'faq',
    'network-analysis',
    'firststeps-locations',
    {
      type: 'category',
      label: 'Support',
      items: [
        "contactsupport",
        "create-screenshots"
      ]
    },
    {
      type: 'category',
      label: 'Account',
      items: [
        "account-termination-and-cancellation-period",
        "account-paymentoptions",
      ]
    },
  ],
  
  
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  gameserverSidebar: [
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "First steps";
        }
      })(),
      defaultStyle: true,
    },
    "gameserver-server-down-what-now",
    "serverfaqs"
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "Popular Games";
        }
      })(),
      defaultStyle: true,
    },
    {
      type: "category",
      label: "Call of Duty 2",
      items: [
        {
        },
        "cod2-firststeps-dashboard"
      ],
    },
    {
      type: "category",
      label: "Call of Duty 4: Modern Warfare",
      items: [
        {
        },
        "cod4-firststeps-dashboard"
      ],
    },
    {
      type: "category",
      label: "Counter-Strike: 1.6",
      items: [
        {
          type: "category",
          label: "Administration",
          items: [
            "cs16-becomeadmin",
          ]
        },
      ],
    },
    {
      type: "category",
      label: "Counter-Strike: Source",
      items: [
        {
        },
        "css-firststeps-dashboard"
      ],
    },
    {
      type: "category",
      label: "Counter-Strike: 2",
      items: [
        {
        },
        "cs2-firststeps-dashboard"
      ],
    },
    {
      type: "category",
      label: "Half-Life: Deathmatch",
      items: [
        {
        },
        "hldm-firststeps-dashboard"
      ],
    },
    {
      type: "category",
      label: "Team Fortress 2",
      items: [
        {
        },
        "tf2-firststeps-dashboard"
      ],
    },                
    {
      type: 'html',
      className: 'sidebar-title',
      value: (() => {
        switch (process.env.DOCUSAURUS_CURRENT_LOCALE) {
          default: return "All Games (A-Z)";
        }
      })(),
      defaultStyle: true,
    },
    {
      type: "category",
      label: "COD",
      items: [
        "cod-firststeps-dashboard"
      ],
    },
    {
      type: "category",
      label: "COD2",
      items: [
        "cod2-firststeps-dashboard"
      ],
    },
    {
      type: "category",
      label: "COD4: MW",
      items: [
        "cod4-firststeps-dashboard"
      ],
    },        
    {
      type: "category",
      label: "CS16",
      items: [
        "cs16-becomeadmin"
      ],
    },
    {
      type: "category",
      label: "CSCZ",
      items: [
        "cscz-firststeps-dashboard"
      ],
    },
    {
      type: "category",
      label: "CSS",
      items: [
        "css-firststeps-dashboard"
      ],
    },          
    {
      type: "category",
      label: "CS2",
      items: [
        "source-gsltoken",
        {
          type: "category",
          label: "Configuration & Administration",
          items: [
            "cs2-becomeadmin"
          ]
        },
        {
          type: "category",
          label: "Plugins / Mods",
          items: [
            "cs2-plugins"
          ]
        },
      ],
    },
    
    
  ],
  
};

export default sidebars;
